### ISSUE TITLE
Doesn't render in the right place

### ISSUE THREAD

**Issue by paradox460** [sgade/atom-sloc#2]
I install this plugin, and it appears not to do anything. But, upon a trip to the inspector, I can see that it is rendering, however, not properly. It renders outside the status bar, likely due to atom template api changes.

![image](https://cloud.githubusercontent.com/assets/168193/7843397/44fc1b14-045e-11e5-9c05-66fd13d10a0d.png)

**Comment by sgade** [comment]
I guess you are right. I haven't updated this plugin for a while now and I already heard Atom has changed it's API. However, I am currently not using Atom anymore nor do I have the time to spend to fix this issue.

It seems to me only a few calls have to be changed to get the view to render correctly, so maybe you can fix it yourself using the up-to-date APIs and send a pull request back? That'd be awesome. :+1:

**Comment by paradox460** [comment]
Sure, I'll take a look

**Comment by sgade** [comment]
Thanks.

**Comment by sgade** [comment]
Is there any progress on this, @paradox460?

**Comment by paradox460** [comment]
I haven't even started. I meant to but work got in the way :cry:

Ill try to work on it again this week

**Comment by sgade** [comment]
Alright, no problem. Just keep this issue up-to-date if you have time to work on the problem as I might find some time to dedicate myself.

**Comment by sgade** [comment]
Version 1.0.0 is now available.
