### ISSUE TITLE
Project sloc

### ISSUE THREAD

**Issue by maasha** [sgade/atom-sloc#3]
How about expanding to include sloc for an entire project?

**Comment by sgade** [comment]
Nice idea. 
How would you implement that feature in the view (without making it endlessly wide)? Pull requests are welcome.

**Comment by maasha** [comment]
One could use cloc:

https://github.com/AlDanial/cloc

It could be included using git submodule:

https://git-scm.com/docs/git-submodule

Unfortunately, I don't write Javascript.

**Comment by sgade** [comment]
I found an [npm package for cloc](https://github.com/kentcdodds/cloc), however, I rather not call into perl from an node *extension* of an editor.
Even if this worked well, there is still the question on how to integrate the results into the view. At first thought, a toggle command came to my mind but then you'd need some indication for the user which mode he is in.

**Comment by maasha** [comment]
Obtaining the project-wide sloc could probably benefit from using an existing solution - and cloc appears to be robust.

I suppose a user just want a popup on demand with project-wide sloc since there is no point in displaying that information while editing.

**Comment by sgade** [comment]
Sure, using cloc itself seems like a good idea although I do not have any
experience with calling Perl from node and the implications that come with
it. That's why I am hesitant.

The idea to show a popup sounds like a good idea.

2015-11-01 17:45 GMT+01:00 Martin Asser Hansen <notifications@github.com>:

**Comment by sgade** [comment]
Closing for now, feel free to ping me with any updates.
